version: 2

updates:
  - package-ecosystem: npm
    versioning-strategy: increase
    open-pull-requests-limit: 10
    directory: "/"

    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Jakarta

    assignees:
      - manferlo81
