version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

executors:
  node:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

jobs:

  unit-test:

    executor: node

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: "Run Tests"
          command: npm test

      - persist_to_workspace:
          root: ~/repo
          paths: .

  upload-coverage:

    executor: node

    steps:

      - attach_workspace:
          at: ~/repo

      - codecov/upload:
          file: coverage/*.json

  publish-pkg:
    executor: node
    steps:

      - attach_workspace:
          at: ~/repo

      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish to npm
          command: npm publish

workflows:
  version: 2

  workflow:
    jobs:

      - unit-test:
          filters:
            tags:
              only: /.*/

      - upload-coverage:
          requires:
            - unit-test
          filters:
            branches:
              ignore: /greenkeeper/

      - publish-pkg:
          requires:
            - unit-test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
