version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

executors:
  node:
    docker:
      - image: circleci/node:10
    working_directory: &cwd ~/repo

commands:
  npm_publish:
    steps:

      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish to npm
          command: npm publish

jobs:

  unit_test:
    executor: node
    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: "Run Tests"
          command: npm test

      - persist_to_workspace:
          root: *cwd
          paths: .

  upload_coverage:
    executor: node
    steps:

      - attach_workspace:
          at: *cwd

      - codecov/upload:
          file: coverage/*.json

  publish_pkg:
    executor: node
    steps:

      - attach_workspace:
          at: *cwd

      - npm_publish

workflows:
  version: 2

  workflow:
    jobs:

      - unit_test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - upload_coverage:
          requires:
            - unit_test
          filters:
            branches:
              ignore: /greenkeeper/

      - publish_pkg:
          context: NPM
          requires:
            - unit_test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
