version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:

  build:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: "Run Tests"
          command: npm test

      - codecov/upload:
          file: coverage/*.json

workflows:
  version: 2

  workflow:
    jobs:
      - build
