version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  executor_node:
    docker:
      - image: cimg/node:12.22
    working_directory: &working_directory ~/rollup-plugin-strip-shebang

commands:
  command_npm_publish:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  job_test_and_build:
    executor: executor_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-rpstsh-{{ checksum "package.json" }}
            - v1-deps-rpstsh-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-deps-rpstsh-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - .

  job_upload_coverage:
    executor: executor_node
    steps:
      - attach_workspace: &attach_workspace
          at: *working_directory
      - codecov/upload:
          file: coverage/*.json

  job_publish_to_npm:
    executor: executor_node
    steps:
      - attach_workspace: *attach_workspace
      - command_npm_publish

workflows:
  workflow_ci:
    jobs:
      - job_test_and_build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_upload_coverage:
          requires:
            - job_test_and_build
          filters:
            branches:
              only: /master/

      - job_publish_to_npm:
          context: npm
          requires:
            - job_test_and_build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
