version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

executors:
  node:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

jobs:

  unit-test:

    executor: node

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: "Run Tests"
          command: npm test

  upload-coverage:

    executor: node

    steps:

      - codecov/upload:
          file: coverage/*.json

workflows:
  version: 2

  workflow:
    jobs:
      - unit-test
      - upload-coverage:
          requires:
            - unit-test
          filters:
            branches:
              ignore: /greenkeeper/
